<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>nightmaregaurav.schedulite</PackageId>
        <VersionPrefix>1.0.0</VersionPrefix>
        <Description>A lightweight and flexible scheduling library for .NET applications.</Description>
        <Authors>Gaurav Nyaupane</Authors>
        <Owners>nightmaregaurav</Owners>
        <Title>Schedulite</Title>
        <PackageProjectUrl>https://github.com/nightmaregaurav/Schedulite</PackageProjectUrl>
        <RepositoryUrl>https://github.com/nightmaregaurav/Schedulite</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Copyright>Copyright ©2026 Gaurav Nyaupane (nightmaregaurav)</Copyright>
        <PackageTags>Scheduling;Cron;Background Jobs;Job Scheduling;Background Processing;Task Automation;Cron Expressions;Task Scheduling Framework</PackageTags>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
